steps:

# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@1
  inputs:
    secureFile: pip.conf
  displayName: 'download pip.conf'

# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@1
  inputs:
    secureFile: .pypirc
  displayName: 'download .pypirc'

- script: |
    mkdir -p ~/.config/pip
    mv $(Agent.TempDirectory)/pip.conf ~/.config/pip/pip.conf
    mv $(Agent.TempDirectory)/.pypirc ~/.pypirc
  displayName: 'move pip credentials'
